Master
Cardinal-Invariants/quest-creator-backend pull request #1
Opened 2020-10-04 18:44 UTC by Qwebeck

2020-10-04 20:42 UTC, Dushess0 commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestStartPoint.java
> +        new Point(11, 12);  // wtf?
Это будет измененно на нормальные данные?

2020-10-04 20:42 UTC, Dushess0 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestService.java
> +    public List<QuestPoint> startPointsInRadiusAroundPlayer(Point userCoordinates, double radius){
Радус земли вроде как разный в разных точках планеты, во вторых он тут округлен. Тестировали ли функцию **startPointsInRadiusAroundPlayer** ?  Думаю лучше использовать или сторонее API для проверки точек в радиусе от пользователя.

2020-10-04 20:42 UTC, Dushess0 commented on src/main/java/com/github/gunghorse/questCreator/FillDB.java
> +        questStartPointRepository.deleteAll();
Почему **questStartPointRepository** существует как отдельный репозиторий? То есть мы имеем репозиторий пользователей, точек, квестов и еще отдельно точек которые явяются началом квестов? Я бы убрал его, ибо не вижу значительных отличий от репозитория обычных точек.

2020-10-04 20:42 UTC, Dushess0 commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestPointStatus.java
> +public enum QuestPointStatus {
Я бы разбил один большой ENUM статуса на два ENUM'а поменьше. Т.е. VISIBLE и INVISIBLE, и VISITED UNVISITED.

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    @JsonIgnoreProperties({"quest","playing","createdQuests"})
@Dimonium-239 
Правильно понимаю, что это поля которые не будут добавлены к запросу который полетит как ответ ?
Если так, то я не уверен, что нам нужно пропускать поле `playing` и поле `createdQuests`

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    public Quest(String title, String description) {
Мы не всегда будем присылать квест с описанием:
может быть так, что мы захотим добавить шаблон квеста, который будет ещё не закончен и у которого будет только `title` или только 'description'
Мы будем это делать конечно на отдельном эндпоинте, но факт в том, что нам нужен конструктор который позволяет это сделать.


Поэтому я бы использовал этот паттерн 

https://dzone.com/articles/design-patterns-the-builder-pattern

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    public QuestStartPoint getStartPoint() {
Не тяжело будет добавить библиотеку в которой есть геттеры и сеттеры ?

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +import com.github.gunghorse.questCreator.quests.points.QuestStartPoint;
Не тяжело будет обрезать названия пакетов к `questCreator` ?
Просто по-моему такие названия выглядят немного отсраненно от проекта
@Dushess0 , @VVlovsky  что вы об этом думаете ?

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +    public QuestController(QuestRepository questRepository,
Предлага ввести конвенцию названий для интерфейсов 
I[InterfaceName]:
IQuestRepository, IQuestPointRepository, etc...
Просто сейчас смотрю и для того чтобы понять интерфейс это или клас, должен искать файл в котором он определен.

@Dushess0, @VVlovsky , ваше мнение  ?

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        return (List<Quest>) questRepository.findAll();
Почему вы делает каст в этом месте, если `findAll `  должен возвращать 'List<Quest>` ?

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * GET /quest/my
Я бы изменил название на 
`quest/userQuests` потому что мне оно кажеться более интуиционным:
это будет странно выглядеть с уровня кода на UI:


```
 // pseudocode
var quests = httpClient.get('/quests/my')

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * GET /quest/my
Ещё я изменил бы тип на POST, потому что нам нужно будет высылать фильтры и нам комортнее будет высылать объект чем `queryString`.

Со стороны бэкенда это не должно ничего изменить кроме декоратора метода, а на фронте упростит работу

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        double longitude = Double.parseDouble(coordsAndRadius.get("lon"));
https://stackoverflow.com/q/32201441/7516134

По-моему так более читабельно

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        if(quest.getPoints().isEmpty()){
Нет проверки на то существует ли квест с таким id.

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        this.questRepository = questRepository;
Мы не смогли найти имплементацию репозитория `QuestRepository`.

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +    public QuestController(QuestRepository questRepository,
В конструкторе нет проверки на nullReference. 
Если вы используете DI, то может быть так, что к интерфейсам не будет привязана импленетация и в этом месте будет null.
Так что я бы добавил проверку

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        User creator = userRepository.findByUsername(principal.getName());
Пользователь может не существовать.

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestService.java
> +        //List<QuestStartPoint> allQuests = ((List<QuestStartPoint>)questStartPointRepository.findAll());
Теперь пишем код вместе, так что предлагаю не добавлять коментарии в таком стиле: если метод не нужен - сразу удаляем
@Dushess0 @VVlovsky  ?

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestPointDTO.java
> +    private String pointStatus;
Я думаю, что здесь тоже должен быть enum `QuestPointStatus `, а не строка

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestStartPoint.java
> +        new Point(11, 12);  // wtf?
wtf ?

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestStartPoint.java
> +public class QuestStartPoint extends QuestPoint {
Я предлагаю обсудить нужно ли добавлять `QuestStartPoint` как отдельный клас

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/security/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
Думаю что где-то здесь также должны определяться CORS.

2020-10-04 20:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/user/UserController.java
> +            return true;
С контроллеров нужно возвращать статус коды:
'200', `400`, ....

2020-10-04 20:52 UTC, VVlovsky requested changes

2020-10-04 20:52 UTC, venglov commented on src/main/java/com/github/gunghorse/questCreator/repositories/QuestRepository.java
> +}
@Dimonium-239 @xenoteo 
Стоило бы поискать другое решение, чтобы не наследоваться от интерфейса базы данных, т.к. иначе код будет слишком сильно привязан к текущей базе данных и в дальнейшем действия по типу смены базы данных будут очень проблематичны. К примеру, реализовать интерфейс и заимплементировать методы самостоятельно с нуля.

2020-10-04 20:52 UTC, venglov commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    private List<User> players = new LinkedList<>();
Почему именно LinkedList? Не уместнее ли было бы использовать ArrayList?

2020-10-04 20:52 UTC, venglov commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * GET /quest/point/onPoint?lon=50.061667&lat=19.937347
Передавать координаты через GET создаёт потенциальную уязвимость, тк юзер сможет передать их браузером и получить ответ, в этом случае стоит использовать POST.
Дополнительно было бы неплохо изменить название на более универсальное aka answerSubmit и дать возможность итерироваться по типам этого сабмита (image/text/location).

2020-10-04 20:52 UTC, VVlovsky commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * POST quest/point/create
Хорошим решением будет разделить квестКонтроллер на aka ActiveQuestController и aka QuestCreationController, т.к. сейчас мы имеем что строки для игры выглядят по типу quest/point/onPoint(submit) и для редактирования/создания quest/point/create, в то время как реализуемая логика отвечает за совершенно разные аспекты игры.

2020-10-04 20:52 UTC, Dushess0 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +    public QuestController(QuestRepository questRepository,
я за приставку I

2020-10-04 21:24 UTC, Qwebeck commented
`java/com/github/gunghorse/pathes`
А ещё я изменил бы название папки на `controllers`

2020-10-05 13:08 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestStartPoint.java
> +        new Point(11, 12);  // wtf?
Это лишняя строка, ее нужно удалить.

2020-10-05 13:09 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/FillDB.java
> +        questStartPointRepository.deleteAll();
Идея репозиториев в том что отдельный репозиторий отвечает за отдельную таблицу в базе данных. Мы приняли, wstępnie, что у нас есть стартовая точка и поэтому для нее созадн репозиторий.

2020-10-05 13:48 UTC, xenoteo commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestService.java
> +    public List<QuestPoint> startPointsInRadiusAroundPlayer(Point userCoordinates, double radius){
Для пунктаў з Кракава функцыя выдавала вынікі вельмі блізкія да праўды. 

Розьніца паміж адлегласьцямі паміж прыкладовымі пунктамі, палічанымі з выкарыстаньнем мінімальнага і максымальнага радыюса Зямлі, менш за 2 м. Таксама палічылі адлегласьць паміж блізкімі пунктамі з выкарыстаньнем сярэднега радыюса, каб параўнаць усе гэтыя адлегласьці паміж сабой. У выніку можна сказаць, што формула ў залежнасьці ад шыраты можа даваць памылкі ад 0.5 да 2 м.

Калі вы хочаце павысіць дакладнасьць на пару дэцымэтраў, то можам разважыць дадаваньне зьнешняга API (калі, канешне, ёсьць нешта, што будзе нашмат дакладнейшым). Ці разважыць, што Зямля - гэта эліпс і вывесьці іншую формулу з выкарыстаньнем інтэгралаў. Толькі мне асабіста гэта здаецца немэтазгодным, бо нават GPS будзе даваць меншую дакладнасьць актуальнага пункту юзэра.

https://www.gps.gov/systems/gps/performance/accuracy/
For example, GPS-enabled smartphones are typically accurate to within a 4.9 m (16 ft.) radius under open sky (view source at ION.org). However, their accuracy worsens near buildings, bridges, and trees.

2020-10-05 13:50 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    @JsonIgnoreProperties({"quest","playing","createdQuests"})
Да, это поля которые не будут добавлены к запросу. Идея этих полей в том что бы избежать рекурсии когда ты получаешь точку в которой есть квест в котором есть точка и тд. И сейчас в данном API небольшая проблема, я бы сказал баг, из-за направлений реляций в базе данных и поэтому насчет присутствия этих полей еще работаем. Не могу сейчас сказать, нужно их удалить или нет, над этим еще нужно поработать

2020-10-05 13:51 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    public Quest(String title, String description) {
Ок, иправим.

2020-10-05 13:52 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    public QuestStartPoint getStartPoint() {
Ты про lombok? Нет, не трудно, добавим.

2020-10-05 13:52 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +import com.github.gunghorse.questCreator.quests.points.QuestStartPoint;
Хорошо, обрежем.

2020-10-05 13:55 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +    public QuestController(QuestRepository questRepository,
Я против приставки I к репозиториям. Против, потому что репозитории, хоть техничиски и являются интерфейсами, практически ими не являются. Repository в конце четко показывает что это за файл и чем он занимается в нашем проекте.

2020-10-05 13:55 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        return (List<Quest>) questRepository.findAll();
Потому что ```findAll``` возвращает ```Iterable<Quest>``` и для этого мы кастим его в ```List<Quest>```

2020-10-05 13:55 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * GET /quest/my
Хоршо, поменяем.

2020-10-05 13:56 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * GET /quest/my
Хорошо, исправим.

2020-10-05 13:56 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        if(quest.getPoints().isEmpty()){
Хорошо, добавим валидацию.

2020-10-05 13:57 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        this.questRepository = questRepository;
Репозитории только номинально интерфейсы, на самом деле это особый механизм который не имплементируется, поэтому вы и не нашли его имплементации.

2020-10-05 13:57 UTC, xenoteo commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestPointStatus.java
> +public enum QuestPointStatus {
Мае сэнс, падумаем пра гэта.

2020-10-05 13:59 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +    public QuestController(QuestRepository questRepository,
Такого произойти не может из-за природы репозиториев.

2020-10-05 14:00 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        User creator = userRepository.findByUsername(principal.getName());
Да, такое может случится. Добавим валидацию.

2020-10-05 14:06 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestService.java
> +        //List<QuestStartPoint> allQuests = ((List<QuestStartPoint>)questStartPointRepository.findAll());
Дико извеняемся за такое поведение. Мотивация данного коментария здесь вот какая: 
Так как мы еще не успели обсудить наличие ```QuestStartPoint``` то данная строка оставлена что бы ее раскоментировать если мы решим что хотим что бы наше API возвращало ближайшие к игроку стартовые пункты.

2020-10-05 14:08 UTC, xenoteo commented on src/main/java/com/github/gunghorse/questCreator/repositories/QuestRepository.java
> +}
Пісаць рэпазыторыі самастойна - гэта тое ж самае, што ў прынцыпе не карыстацца Spring'ам. Раўназначна таму, што пісаць сайты на чыстых HTML, CSS i JS. Мы выкарыстоўваем Spring, каб мець менш boilerplate code. Spring генеруе імплементацыю гэтых інтэрфэйсаў аўтаматычна, і пры зьмене базы даных адзінае, што трэба будзе зьмяніць, гэта назва класу, па якім мы робім extends.

2020-10-05 14:08 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestPointDTO.java
> +    private String pointStatus;
Согласен, только не знаю как переслать тип enum через HTTP.

2020-10-05 14:09 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestStartPoint.java
> +        new Point(11, 12);  // wtf?
Лишняя строка, нужно удалить.

2020-10-05 14:10 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestStartPoint.java
> +public class QuestStartPoint extends QuestPoint {
Согласны, что это нужно обсудить.

2020-10-05 14:12 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/security/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
Не компетентны ничего ответить по поводу CORS. Первый раз об этом слышим.

2020-10-05 14:12 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/user/UserController.java
> +            return true;
Согласны, исправим.

2020-10-05 14:14 UTC, xenoteo commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    private List<User> players = new LinkedList<>();
Залежыць ад таго, якія ў нас мэты і навошта мы дадаем лісту людзей, якія ў цяперашні момант граюць у выбраны квэст. Калі гэта настолькі прынцыпова, можам вынесьці гэтае пытаньне на сустрэчу і разам ўсё абмеркаваць.

2020-10-05 14:15 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * GET /quest/point/onPoint?lon=50.061667&lat=19.937347
Так сделано для простоты тестирования и показания функциональности.

2020-10-05 14:16 UTC, Dimonium-239 commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * GET /quest/point/onPoint?lon=50.061667&lat=19.937347
Если то, как работает это функция вам всем вчера понравилась то поменяем с GET на POST

2020-10-05 14:17 UTC, xenoteo commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * POST quest/point/create
Ок, мае сэнс, зробім.

2020-10-05 14:18 UTC, merged

2020-10-05 20:55 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestService.java
> +    public List<QuestPoint> startPointsInRadiusAroundPlayer(Point userCoordinates, double radius){
Я думаю, что если будут какие-то проблемы с этим, то потом можем поправить, а пока что можем не волноваться

2020-10-05 20:56 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestPointStatus.java
> +public enum QuestPointStatus {
@xenoteo 
Напишиет здесь, когда что-то решите

2020-10-05 21:03 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    @JsonIgnoreProperties({"quest","playing","createdQuests"})
Можно попробовать написать свой json конвертер в котором указать какие поля с точки (или с квеста) нужно сериализировать ( чтобы избежать рекурсии ) 
https://www.baeldung.com/jackson-custom-serialization

2020-10-05 21:03 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    public Quest(String title, String description) {
Супер :)

2020-10-05 21:03 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +import com.github.gunghorse.questCreator.quests.points.QuestStartPoint;
Отлично, спасибо

2020-10-05 21:18 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +    public QuestController(QuestRepository questRepository,
@Dimonium-239 
А чем тогда должны заниматься интерфейсы если не показывать что это за файл и чем он занимаеться в наше проекте ?

Смысл интерфейса в том, чтобы всегда было известно какие функции мы можем ожидать от нашего обьекта. Нас не интересует имплементация, мы хотим знать только то, что он может сделать.


Плюс здесь репозиторий тоже не являеться конкретным обьектом. Он являеться интерфейсом к которому с помощью DI в рантайме была привязана имплементация, которую предоставил нам Neo4j.

DI  ( dependency injection ) - это такая вещь, которая позволяет использовать во всю чудеса полиморфизма. В какой способ ?

В упрощение это можно описать так, что в памяти храниться какой-то словарь в котором определены связки между интерфейсами и конкретными класами которые имплементируют интерфейс в этом проекте:
```
DependencyInjectionProvider provider = {
   QuestRepository:  Neo4JConcreteQuestRepositoryFactory // что-то что позволяет создать конретный объект этого типа. 

```
Потом, в моменте когда создаеться котролер Spring ( или другой используемый фреймворк который обслужывает DI ) ищет в этом словаре соответсвущие ключи ( интерфейсы ) создает конкретные объекты и передает их в конструктор . А узнает он о том какие именно нужны интерфейсы для конструктора скорее всего с помощью похожего механизма
https://www.oracle.com/technical-resources/articles/java/javareflection.html

2020-10-05 21:20 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestPointDTO.java
> +    private String pointStatus;
https://www.baeldung.com/spring-enum-request-param

Вроде здесь описано

2020-10-05 21:21 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/points/QuestStartPoint.java
> +        new Point(11, 12);  // wtf?
Хорошо :) 
Если что, то предыдущий кометарий тоже был написан не со злостью ;)

2020-10-05 21:25 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/security/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Если коротко, то это то что ограничивает доступ к твоему апи с других адресов, кроме твоего апи. 

То есть предположим, у тебе есть сервис который постит смешные картинки котиков. 
И ты хочешь, чтобы на котиков могли смотреть только люди которые приходят с сайта `http://lovely-cats.com`
А все другие запросы должны отбрасываться.
Тогда ты добавляешь в CORS с помощью чего то в стиле 
```
Host.AllowCrossOrigin(http://lovely-cats.com)
```
И тогда только запросы с этого сайта будут получать какой-то ответ

2020-10-05 21:25 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/user/UserController.java
> +            return true;
Отлично

2020-10-05 21:49 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/repositories/QuestRepository.java
> +}
Не знали об этом, дейстивтельно отличная функциональность. 

Но ты не совсем права, когда говоришь, что все что нужно будет сделать - это изменить навзание класа который мы расширяем.
Вот пример методов которые специфичны именно для репозитория с Neo4j:
![image](https://user-images.githubusercontent.com/21079319/95135032-22637700-0764-11eb-9d15-7be7e938137a.png)

Так что если мы будем где-то использовать например findAll(int depth), а потом изменим репозиторий и базу на например моногдб или какую-то реляционную, то нам нужно будет как-то перегружать метод findAll by depth.
Я не спорю, что нам нужно будет также перегружать метод с этой функциональонстью и в случае если мы не будем использовать наследование от репозитория, но тогда он может иметь более осмысленное название ( например findAllRelated ) и тогда в случае Neo4j он будет вызывать findAll(int depth), а в случае другой базы - вызывать какой-то другой метод

Как мне кажеться, лучше сделать так, что у нас будет два репо: один который наследуеться от Neo4j, а второй (QuestRepositoryProvider) который будет предоставлять то апи которое мы хотим и его имплементация будет под собой использовать то, репозиторий от Neo4J.

Но я не думаю, что мы собираемся менять базу, так что нам это вряд ли заболит. 
А это действительно уменьшает к-во повторяемого кода, так что вполне может быть

2020-10-05 21:51 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    private List<User> players = new LinkedList<>();
По-моему вообще не принципиально.
Я думаю что вполне может быть и `LinkedList'

2020-10-05 21:52 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * GET /quest/point/onPoint?lon=50.061667&lat=19.937347
Супер :)
Просто в будущем может быть много разных типов ответа и такие данные лучше присылать с постом

2020-10-05 22:09 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/FillDB.java
> +        questStartPointRepository.deleteAll();
Я бы сказал, что один репозиторий отвечает за один источник данных, который не обязятельно должен быть таблицей (это может быть несколько таблиц которые вместе дают объект). Например репозиторий `Quest` вполне мог бы иметь данные о своей начальней точке.
Главное задание репозитория, как мне кажеться - это добавление независимости от того движка базы данных который мы используем

2020-10-05 22:09 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/Quest.java
> +    public QuestStartPoint getStartPoint() {
Супер, спасибо

2020-10-05 22:12 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        return (List<Quest>) questRepository.findAll();
Я думаю, что с этой функции вполне можно возвращать Iterable<Quest> потому что результат все равно будет конвертирован к JSON, а для этого, касколько я знаяю не нужен список

2020-10-05 22:13 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +     * GET /quest/my
Спасибо :)

2020-10-05 22:20 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +    public QuestController(QuestRepository questRepository,
Может если в проекте не будет заимплементирован этот репозиторий. Или же если он будет неправильно сконфигрирован. Сейчас этого скорее всего не произойдет потому что проект ещё маленький, но когда он вырастет, то такие вещи могут появиться. И тогда я бы предпочел, чтобы NullReference был выброшен в конструкторе, а не в каком-то из методов, потому что тогда я буду уверен, что этот параметр не пришел в коструктор, а не что он был изменен во время рантайма

2020-10-05 22:20 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestController.java
> +        User creator = userRepository.findByUsername(principal.getName());
Супер, спасибо

2020-10-05 22:23 UTC, Qwebeck commented on src/main/java/com/github/gunghorse/questCreator/quests/QuestService.java
> +        //List<QuestStartPoint> allQuests = ((List<QuestStartPoint>)questStartPointRepository.findAll());
Не нужно извиняться, ничего страшного. Это все таки не работа и все мы здесь друзью :) 
Просто учтём на будущее . Я думаю, что такая функциональность может понадобиться и поэтому  вполне можно раскментировать
@Dushess0 @VVlovsky  ?